### ISSUE TITLE
Related Products

### ISSUE THREAD

**Issue by pmapindia** [pmapindiadotcom/pmapecommerce#6]
FMCustomerLastViewedProductAdd

In this API, if that particular product for that customer already existed in database, do not insert

just write one stored procedure.... already exist

**Comment by Harishdspmap** [comment]
> FMCustomerLastViewedProductAdd
> 
> In this API, if that particular product for that customer already existed in database, do not insert
> 
> just write one stored procedure.... already exist

Done Sir.

**Comment by pmapindia** [comment]
Checked by Prasad
