### ISSUE TITLE
ProductList - Alignment issues 

### ISSUE THREAD

**Issue by pmapindia** [pmapindiadotcom/pmapecommerce#9]
- Product price should be end of product name
- Product highlights, should be separated by |, and then display each in next line, 
- Discount should have word off, example 5% off, and it should be in green color
- If rating is 0, then do not show ratings word, same for review also
- Temporarily hide Filters block, 
- Temporarily hide sort by also
- Showing 1-20 of 1340 results of matches, hide this also, once we done it, then we can show it,...
- On click on product block, it should redirect to product details page, currently not happening

![image](https://user-images.githubusercontent.com/20572033/236677583-a094b823-fc65-45a5-a34d-ab9f8d53716e.png)

http://localhost:2000/#/product-list?search=Cadbury

**Comment by Harishdspmap** [comment]
Done Sir
